config/routes.rb
Myfirstsite::Application.routes.draw do
  resources :jobresults

end

app/models/jobresult.rb
class Jobresult < ActiveRecord::Base
   # attr_accessible :title, :body

 def jobsearch(options={})
   result = self.class.get("http://api.careerbuilder.com/v1/jobsearch?", :query => {:DeveloperKey => "WDHQ4VK5ZGXFY0PDH094",:outputjson => true})
   # puts "s"
    return result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include HTTParty
	base_uri "http://api.careerbuilder.com"

# intailizing the host site
def intailize(hostsite="US")
@hostsite=hostsite
end

#Defining the developer key
def default_developerKey
 	{:DeveloperKey=>"WDHQ4VK5ZGXFY0PDH094"}
end 

 #defining hoststite
 def default_hostsite
  	{:Hostsite=>@hostsite}
 end

 def mashup(response)
    puts response.inspect
    case response.code
      when 200
        if response.is_a?(Hash)
          Hashie::Mash.new(response)
        else
          if response.first.is_a?(Hash)
            response.map{|item| Hashie::Mash.new(item)}
          else
            response
          end
        end
    end
  end


def LoadJobs(options={})
		#API Access
	mashup(self.class.get("/v1/jobsearch?", :query => options.merge(self.default_developerKey).merge(self.default_hostsite)))
end
  

end

app/controllers/jobresults_controller.rb
class JobresultsController < ApplicationController

def index
     if !params[:keywrd].blank? &&!params[:loc].blank?
        @jobresults= LoadJobs(:Keyword=>params[:keywrd],:location=>params[:loc])
      elsif !params[:keywrd].blank? && params[:loc].blank?
        @jobresults= LoadJobs(:Keyword=>params[:keywrd])
      elsif params[:keywrd].blank? && !params[:loc].blank?
        @jobresults=LoadJobs(:location=>params[:loc])
      else
          @jobresults=LoadJobs(:Keyword=>"")      
       end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobresults_helper.rb
module JobresultsHelper
end

app/views/jobresults/_form.html.erb
<%= form_for(@jobresult) do |f| %>
  <% if @jobresult.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jobresult.errors.count, "error") %> prohibited this jobresult from being saved:</h2>

      <ul>
      <% @jobresult.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobresults/edit.html.erb
<h1>Editing jobresult</h1>

<%= render 'form' %>

<%= link_to 'Show', @jobresult %> |
<%= link_to 'Back', jobresults_path %>

app/views/jobresults/index.html.erb
<h1>Find the best suited job for you</h1>

<div class="searchBox" style="margin-top:10px;">
  <%= form_tag("/jobresults", method: "get") do %>
      <h3 style="float:left; margin-top: -8px;">Refine your search: &nbsp;</h3>
      <%= text_field_tag(:keywrd, nil, :placeholder => "Keyword") %>
      <%= text_field_tag(:loc, nil, :placeholder => "location") %>
      <%= submit_tag("Find Jobs", style: "height:28px;margin-top:-12px;") %>
  <% end %>
</div>

<div class="maincontent" >
 <div class="jobList">
    <% unless @jobresults.blank? %>

        <% if @jobresults.ResponseJobSearch.TotalCount == 0 %>
            No jobs found for your search criteria
        <% else %>

            <% @jobresults.ResponseJobSearch.Results.JobSearchResult.each do |result| %>
                <div class="resultItem">
                  <br>
                  
                  <br>
                  Location : <%= result.Location %>
                  <br><br>
                  Descripion : <%= result.DescriptionTeaser %>
                  <br><br>
                  <hr>
                </div>
            <% end %>
        <% end %>
    <% end %>
    </div>
</div>

app/views/jobresults/new.html.erb
<h1>New jobresult</h1>

<%= render 'form' %>

<%= link_to 'Back', jobresults_path %>

app/views/jobresults/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_jobresult_path(@jobresult) %> |
<%= link_to 'Back', jobresults_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myfirstsite</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>